### ISSUE TITLE
International Day: May 23rd, 2015

### ISSUE THREAD

**Issue by shime** [nodeschool/zagreb#1]
[Dino Trojak](https://twitter.com/dinodsaurus) and me are hosting the first Croatian NodeSchool event. Join us at [MOP Fest](https://mop-fest.com) @ palača Herzer Franjevački trg 6, Varaždin.

We're starting @ around 13:00, bring your laptops.

**Comment by iancrowther** [comment]
in order to be included in the day you MUST add your details to:
- https://github.com/nodeschool/international-day/issues/8
- https://github.com/nodeschool/international-day/issues/22

Otherwise you will not appear on the landing page.

Enjoy the event

**Comment by iancrowther** [comment]
https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md#enrollment
